mod driver_download_link_config;
mod driver_page_config;
mod driver_release_notes_link_scraper_config;
mod driver_version_scraper_config;

pub use driver_download_link_config::DriverDownloadLinkScraperConfig;
pub use driver_page_config::DriverPageConfig;
pub use driver_release_notes_link_scraper_config::DriverReleaseNotesLinkScraperConfig;
pub use driver_version_scraper_config::DriverVersionScraperConfig;
